const posts=[
{type:'THOUGHTS · 08.28.2026',title:'在噪声里，给自己留一小块静音区',deck:'有时候我们需要的不是新的输入，而是重新听见自己。',body:`<p>有一阵子，我把“及时回复”当作一种能力。手机在桌上亮一下，手指就立刻伸过去；网页上出现一个新标签，注意力就跟着跑掉。一天结束时，屏幕使用时间很长，却说不出自己真正完成了什么。</p><p>后来我试着在傍晚把通知关掉，给自己留出半小时的静音区。没有目标，也不强迫自己读完什么。只是泡茶、望着窗外，或者把白天没来得及想清楚的事情慢慢捡回来。</p><h2>把注意力还给自己</h2><p>我们总把安静误会成空白。其实它更像一张没有画满的纸：你终于可以选择留下些什么。可能是一句突然想通的话，可能是明天要记得买的一束花，也可能只是好好发一次呆。</p><blockquote>安静不是把世界关在门外，而是给内心腾出一点位置。</blockquote><p>现在我会在每次工作结束后，特意让桌面空下来。关掉不必要的页面，把耳机摘下来，走到阳台上看几分钟天色。世界并没有因为我离线而失去什么，但我却慢慢找回了自己的节奏。</p><p>如果你也觉得被信息推着走，不妨从十分钟开始。十分钟不看消息、不打开推荐页。把它当成送给自己的一个小小的房间。</p>`},
{type:'PLAYLIST · 08.17.2026',title:'适合一个人散步时听的 12 首歌',deck:'耳机里的小宇宙，和城市一起缓慢移动。',body:`<p>这份歌单没有很明确的主题。它适合傍晚六点半的街道、雨后反光的地面，或者回家的末班车。它们不会催促你抵达哪里，只是让路变得不那么长。</p><h2>Side A · 走出门的前十分钟</h2><p>01. Midnight City · M83<br>02. Sunset Lover · Petit Biscuit<br>03. Space Song · Beach House<br>04. Young Folks · Peter Bjorn and John</p><p>前几首最好在刚出门的时候播放。城市还没有完全暗下来，风从建筑之间穿过，所有事情看上去都有一点电影感。</p><h2>Side B · 把脚步放慢</h2><p>05. Plastic Love · 竹内まりや<br>06. 505 · Arctic Monkeys<br>07. Sweet Disposition · The Temper Trap<br>08. Cherry-coloured Funk · Cocteau Twins</p><blockquote>有些歌不是为了听清歌词，而是为了让你在某个路口停一下。</blockquote><p>剩下四首留给你自己补齐。音乐是一件很私人的事，最好的歌单总有一部分是别人无法替你写下的。</p>`},
{type:'DIGITAL LIFE · 08.09.2026',title:'我们如何与算法保持一点距离？',deck:'把选择权从推荐页拿回来。',body:`<p>算法不是敌人。它只是特别懂得如何延长我们的停留：下一条更有趣、下一个视频更接近你的喜好、下一次刷新更像一次小小的承诺。</p><p>真正值得担心的不是被推荐，而是我们逐渐忘记了主动寻找的感觉。喜欢什么、讨厌什么、想把时间花在哪里，本来都是很需要练习的能力。</p><h2>一个笨拙但有效的小规则</h2><p>我给自己定过一条规则：每周至少主动找一部电影、一张专辑和一篇长文。它们不一定会比推荐内容更好，但我必须自己想办法找到它们。</p><blockquote>选择不一定高效，却会让生活重新带一点自己的弧线。</blockquote><p>有时候我从一本书的致谢里找到下一本书；有时候顺着朋友的播放列表，走到完全陌生的音乐里。这样的路径有一点绕，却很真实。</p><p>把选择权从推荐页拿回来，不是拒绝便利，而是提醒自己：我不只是一个被不断计算的停留时长。</p>`},
{type:'FRAGMENTS · 07.30.2026',title:'七月的云、冰美式和一张没拍好的照片',deck:'一些不值得忘记的小事。',body:`<p>那天的云被风吹得很低，像一整片没有晾干的白色衬衫。冰美式外面挂着水珠，桌上的相机忽然没电。</p><p>后来照片拍到了，但构图歪了，光线也过曝。我本来打算删掉它，最后还是留在了相册里。</p><h2>不完美的证据</h2><p>我们太习惯删掉不够好的东西：失焦的照片、说得不够漂亮的话、没有完成的草稿。可回头看时，那些被留下来的瑕疵反而最像生活。</p><blockquote>有些记录不需要漂亮。它们只是替我们证明：那天下午的风，真的吹过。</blockquote><p>于是我把照片保留在了“July”文件夹。也许很多年以后再打开，我不会记得咖啡是什么味道，但会记得那天的光。</p>`},
{type:'LITTLE LOGS · WEEK 35',title:'在雨天读完一本旧书',deck:'一场雨，一本被翻过很多次的书。',body:`<p>雨声很适合读旧书。它会把房间里所有不必要的声音都盖过去，剩下纸页翻动的轻响。</p><p>书里有一行被前一个读者画了铅笔线，我停在那里很久。陌生人隔着十几年留下一点痕迹，而我刚好在这个阴天读到它。</p><blockquote>时间也许没有想象中那么直线。</blockquote><p>合上书的时候天已经暗了。窗上有很多水痕，像没来得及送出的句子。</p><p>我把书放回书架时，忽然有点想感谢那个用铅笔画线的人。也许读书的意义之一，就是让我们在不同的时间里，安静地成为彼此的同路人。</p>`},
{type:'LITTLE LOGS · WEEK 34',title:'关于“慢一点”这件事',deck:'给每一个决定留出一点回声。',body:`<p>慢一点不是拖延，也不是逃跑。它更像是给每一个决定留出回声。</p><p>我们太习惯迅速回答“可以”“没问题”“我马上做”。但有些事如果多等十分钟，也许就能分清：这是我真的想做的，还是只是害怕错过。</p><blockquote>把步子放稳，也是一种勇敢。</blockquote><p>希望这个秋天，我们都能练习慢一点。先把每顿饭吃完，再回答不需要立刻回答的问题；把日历里的空白当成一件需要保护的事。</p><p>慢下来之后，生活不会变小。反而会有更多细节重新出现：路边桂花的味道、朋友说话时短暂的停顿、傍晚天色转暗前那一层很淡的金色。</p>`},
{type:'LITTLE LOGS · WEEK 33',title:'最近的桌面、色彩与梦',deck:'蓝色、夜晚和一份尚未开始的灵感。',body:`<p>我的桌面最近是一张偏蓝的夜景图。没有放太多图标，只有一个写着“later”的文件夹，里面塞满了还没开始的灵感。</p><p>这一周常常梦见海边，也许是因为我把房间的灯换成了很淡的蓝色。颜色有时候比语言更早抵达心里。</p><blockquote>把还没发生的事，也温柔地放进明天。</blockquote><p>我把这个周报写在凌晨一点。屏幕上只开着一盏台灯，窗外很安静。希望明天醒来时，那个“later”文件夹里会有一件事被真正开始。</p><p>晚安，下一周见。</p>`}
];
const index=Math.max(0,Math.min(posts.length-1,Number(new URLSearchParams(location.search).get('id'))||0));const post=posts[index];document.title=`Lusiya — ${post.title}`;document.querySelector('#type').textContent=post.type;document.querySelector('#title').textContent=post.title;document.querySelector('#deck').textContent=post.deck;document.querySelector('#date').textContent=post.type.split(' · ').pop();document.querySelector('#content').innerHTML=post.body;document.querySelector('#copy').addEventListener('click',async()=>{await navigator.clipboard.writeText(location.href);document.querySelector('#copy').innerHTML='<i class="icon-check"></i> 已复制';});
